// app/(tabs)/watch/booking.styles.ts
import { colors } from "@/constants/booking.data";
import Colors from "@/constants/Colors";
import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  rootWrapper: {
    flex: 1,
    backgroundColor: "#FFFFFF",
  },
  portraitScrollContainer: {
    paddingBottom: 40,
  },
  landscapeSplitWrapper: {
    flex: 1,
    flexDirection: "row",
  },
  leftLandscapePanel: {
    width: "48%",
    borderRightWidth: 1,
    borderRightColor: "#EFEFEF",
    paddingHorizontal: 16,
    paddingTop: 12,
  },
  rightLandscapePanel: {
    flex: 1,
    paddingHorizontal: 20,
    paddingTop: 12,
  },
  sectionTitleLabel: {
    fontSize: 16,
    fontWeight: "700",
    color: "#202020",
    marginVertical: 14,
    paddingHorizontal: 16,
    fontFamily: "Poppins-Medium",
  },
  dateSliderHorizontalList: {
    paddingHorizontal: 12,
    marginBottom: 16,
  },
  dateBadgeCapsule: {
    backgroundColor: "#F5F5F7",
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 14,
    alignItems: "center",
    marginHorizontal: 4,
    minWidth: 54,
  },
  dateBadgeCapsuleActive: {
    backgroundColor: Colors.btnbg,
  },
  dateDayNumberText: {
    fontSize: 14,
    fontWeight: "700",
    color: "#202020",
  },
  dateMonthStringText: {
    fontSize: 11,
    color: "#8E8E93",
    marginTop: 2,
    fontFamily: "Poppins-Medium",
  },
  textLightColor: {
    color: "#FFFFFF",
    fontFamily: "Poppins-Medium",
  },
  sessionCardsRow: {
    flexDirection: "row",
    paddingHorizontal: 12,
    gap: 12,
    marginBottom: 20,
  },
  sessionCardContainer: {
    flex: 1,
    borderWidth: 1,
    borderColor: "#EFEFEF",
    borderRadius: 10,
    padding: 12,
    backgroundColor: "#FAFAFC",
  },
  sessionTimeText: {
    fontSize: 13,
    fontWeight: "700",
    color: "#202020",
    marginBottom: 2,
    fontFamily: "Poppins-Medium",
  },
  sessionHallNameText: {
    fontSize: 11,
    color: "#8E8E93",
    marginBottom: 8,
    fontFamily: "Poppins-Medium",
  },
  sessionMiniMapPlaceholder: {
    height: 60,
    backgroundColor: "#EAEAEA",
    borderRadius: 6,
    marginBottom: 8,
    opacity: 0.6,
  },
  sessionPriceTagLabel: {
    fontSize: 11,
    color: "#202020",
    fontWeight: "600",
  },
  sessionBonusTagLabel: {
    fontSize: 10,
    color: "#8E8E93",
    fontFamily: "Poppins-Medium",
  },
  theaterStageArch: {
    width: "80%",
    height: 6,
    backgroundColor: "#DBDBDF",
    alignSelf: "center",
    borderRadius: 3,
    marginVertical: 16,
  },
  seatingGridBodyContainer: {
    paddingHorizontal: 12,
    alignItems: "center",
    marginBottom: 16,
  },
  seatingRowCluster: {
    flexDirection: "row",
    marginVertical: 3,
    alignItems: "center",
    justifyContent: "center",
  },
  seatSquareElement: {
    width: 14,
    height: 14,
    borderRadius: 3,
    backgroundColor: "#DBDBDF",
    marginHorizontal: 3,
  },
  seatSquareRegular: { backgroundColor: "#DBDBDF" },
  seatSquareVip: { backgroundColor: "#2E274C" },
  seatSquareSelected: { backgroundColor: "#FFCC00" },
  seatSquareReserved: { backgroundColor: "#E0E0E0", opacity: 0.4 },
  legendContainerGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    paddingHorizontal: 16,
    gap: 16,
    justifyContent: "center",
    marginVertical: 16,
  },
  legendItemNode: {
    flexDirection: "row",
    alignItems: "center",
    minWidth: 100,
  },
  legendIndicatorSquare: {
    width: 14,
    height: 14,
    borderRadius: 3,
    marginRight: 8,
  },
  legendDescriptorLabel: {
    fontSize: 12,
    color: "#8E8E93",
    fontWeight: "500",
    fontFamily: "Poppins-Medium",
  },
  summaryCheckoutStickyBar: {
    borderTopWidth: 1,
    borderTopColor: "#EFEFEF",
    backgroundColor: "#FFFFFF",
    paddingHorizontal: 24,
    paddingVertical: 16,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  priceSummaryLayout: {
    justifyContent: "center",
  },
  totalPriceHeaderLabel: {
    fontSize: 11,
    color: "#202020",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  totalPriceSumValue: {
    fontSize: 20,
    fontWeight: "700",
    color: "#202020",
    marginTop: 2,
  },
  checkoutActionButton: {
    backgroundColor: Colors.btnbg,
    borderRadius: 10,
    paddingHorizontal: 32,
    height: 48,
    justifyContent: "center",
    alignItems: "center",
  },
  checkoutActionLabel: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "700",
    fontFamily: "Poppins-Medium",
  },
  screen: {
    flex: 1,
    backgroundColor: Colors.primarybg,
  },
  head: {
    backgroundColor: "#fff",
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  headRow: {
    height: 68,
    justifyContent: "center",
    alignItems: "center",
  },
  back: {
    position: "absolute",
    left: 16,
    top: 22,
  },
  title: {
    fontSize: 18,
    fontWeight: "500",
    color: colors.text,
    fontFamily: "Poppins-Medium",
  },
  subtitle: {
    fontSize: 13,
    color: colors.blue,
    marginTop: 4,
    fontFamily: "Poppins-Medium",
  },
  heading: {
    fontSize: 18,
    fontWeight: "600",
    color: colors.text,
    marginBottom: 16,
    fontFamily: "Poppins-Medium",
  },
  chip: {
    paddingHorizontal: 20,
    paddingVertical: 14,
    borderRadius: 10,
    backgroundColor: colors.chip,
  },
  chipActive: {
    backgroundColor: colors.blue,
  },
  chipText: {
    fontSize: 14,
    fontWeight: "500",
    color: colors.text,
    fontFamily: "Poppins-Medium",
  },
  cardHead: {
    flexDirection: "row",
    alignItems: "baseline",
    gap: 8,
    marginBottom: 10,
  },
  time: {
    fontSize: 16,
    fontWeight: "500",
    color: colors.text,
    fontFamily: "Poppins-Medium",
  },
  cinema: {
    fontSize: 14,
    color: colors.muted,
    fontFamily: "Poppins-Medium",
  },
  card: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: "#fff",
  },
  cardActive: {
    borderColor: colors.blue,
    borderWidth: 2,
  },
  from: {
    marginTop: 10,
    fontSize: 14,
    color: colors.muted,
  },
  bold: {
    fontWeight: "700",
    color: colors.text,
    fontFamily: "Poppins-Medium",
  },
  preview: {
    alignItems: "center",
    paddingVertical: 18,
  },
  arc: {
    width: "70%",
    height: 10,
    marginBottom: 6,
    borderTopWidth: 1,
    borderColor: colors.blue,
    borderTopLeftRadius: 100,
    borderTopRightRadius: 100,
  },
  dot: {
    width: 4,
    height: 4,
    margin: 1,
    borderRadius: 1,
  },
  button: {
    height: 52,
    borderRadius: 12,
    backgroundColor: colors.blue,
    alignItems: "center",
    justifyContent: "center",
  },
  buttonText: {
    fontSize: 15,
    fontWeight: "600",
    color: "#fff",
    fontFamily: "Poppins-Medium",
  },
});
export default styles;
